services:
  server:
    image: ${BACKEND_IMAGE:-registry.local/microtube/main-service:latest}
    volumes:
      - ./data/logs:/opt/app/logs
    networks:
      - default
    ports:
      - ${PUBLISHED_PORT:-8080}:8080
    depends_on:
      mysql.db:
        condition: service_healthy
    healthcheck:
      test: sh -c "curl -f http://localhost:8080${SERVER_BASE_PATH-}/healthcheck"
      interval: 20s
      timeout: 10s
      retries: 10
    develop:
      watch:
        - action: rebuild
          path: .
    environment:
      # Application configs
      SPRING_ACTIVES_PROFILE: prod
      SERVER_BASE_PATH: ${SERVER_BASE_PATH-}
#      LOGGING_CONFIG_FILEPATH=/app/config/logback-spring.xml
      # Database configs (may put this to .env file)
      MAIN_DB_URL: r2dbc:mysql://${MAIN_DB_ADDR:-mysql.db:3306}/${MAIN_DB_NAME:-MICROTUBE}
      MAIN_DB_USERNAME: ${DATABASE_USERNAME:-dbuser}
      MAIN_DB_PASSWORD: ${DATABASE_PASSWORD:-123}
      FLUENTD_HOST: ${FLUENTD_HOST:-fluentd}
      FLUENTD_PORT: ${FLUENTD_PORT:-24224}
      ZIPKIN_ENDPOINT: ${ZIPKIN_ENDPOINT:-http://zipkin:9411/api/v2/spans}
#    logging:
#      driver: fluentd
#      options:
#        fluentd-address: ${FLUENTD_ADDRESS:-localhost:24224}
#        tag: "{{.ImageName}}"
#        fluentd-async:
##        fluentd-async-reconnect-interval: 2s
#        fluentd-buffer-limit: 524288
##        fluentd-retry-wait: 1
##        fluentd-max-retries: 4294967295
#        fluentd-sub-second-precision:

#volumes:
#  server-log:
#    driver: local

networks:
  default:

#  secrets:
#    db-password:
#     file: db/password.txt
